### ISSUE TITLE
Sanitization of Swagger parameters does not include Python keywords

### ISSUE THREAD

**Issue by kadrach** [Yelp/bravado-core#289]
```
parameters:                                                    
  - in: "body"                                                   
    name: "from"                                                 
    description: "Pet object that needs to be added to the store"
    required: true                                               
    schema:                                                      
      type: object                                               
```

```
s.pet.post_pet()
...
SwaggerMappingError: from is a required parameter
```

```
s.pet.post_pet(from={})
                      ^
SyntaxError: invalid syntax
```

It looks like the sanitization of parameter names does not check for Python keywords. Is there another API available fire the request that avoids this issue?
