### ISSUE TITLE
Swagger yaml validation reliant on ordering 

### ISSUE THREAD

**Issue by lguo52** [Yelp/bravado-core#301]
Depending on the ordering of properties, validation will return different errors for this problem:

This validation error 
```
jsonschema.exceptions.ValidationError: '@type' is a required property
Failed validating 'required' in schema:
```

occurs when a discriminator (which is also a required property) is not included in the payload to be validated.  However, if discriminator is defined after the required property is, the error returned is a KeyError.

Example:
```
  Food:
    type: object
    properties:
      '@type':
        type: string
        enum:
        - GRAIN
        - FRUIT
        - VEGETABLE
        - DAIRY
        - MEAT
      name:
        type: string
        example: Apple
    required:
    - '@type'
    - name
    discriminator: '@type'
```

versus 

```
  Food:
    type: object
    properties:
      '@type':
        type: string
        enum:
        - GRAIN
        - FRUIT
        - VEGETABLE
        - DAIRY
        - MEAT
      name:
        type: string
        example: Apple
    discriminator: '@type'
    required:
    - '@type'
    - name
```
